################################################################################
# NAME
#    Makefile
#
# DESCRIPTION
#    Arquivo Makefile para compilar o programa getip.c.
#
# AUTHOR
#    Jose Lopes de Oliveira Junior < jlojunior (at) gmail.com >
#
# DATE
#    2006/10
################################################################################

# Variaveis
compiler = gcc
source = getip.c
binary = getip

compile: $(source)
	$(compiler) -o $(binary) $(source)

all: compile

# EOF